[package]
name = "args_test"
version = "0.1.0"
authors = ["boris <oofpgit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
